name: Continuous integration

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: 'Test (PHP: ${{ matrix.php-versions }}, OS: ${{ matrix.operating-systems }})'
    runs-on: ${{ matrix.operating-systems }}

    # STRATEGY
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        operating-systems: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      # SETUP
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, mbstring
      - name: Get Composer cache directory
        id: composer-cache-directory
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-directory.outputs.dir }}
          key: ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}_composer_${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}_composer
            ${{ matrix.operating-systems }}_php${{ matrix.php-versions }}
            ${{ matrix.operating-systems }}
        id: composer-cache
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-suggest

      # TESTS
      - name: Run tests
        run: ./vendor/bin/phpunit

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: dom, mbstring
      - name: Get Composer cache directory
        id: composer-cache-directory
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-directory.outputs.dir }}
          key: ubuntu-latest_php7.4_composer_${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ubuntu-latest_php7.4_composer
            ubuntu-latest_php7.4
            ubuntu-latest
        id: composer-cache
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-suggest

      # TESTS
      - name: Run lint
        run: ./vendor/bin/phpcs ./src ./tests --standard=PSR12